apiVersion: v1
kind: Template
metadata:
  name: jenkins-sa-template
objects:
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: ${PROJECT_NAME}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jenkins
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jenkins-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: jenkins
  rules:
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - clusterrolebindings
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - project.openshift.io
    resources:
    - projects
    - projectrequests
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - customresourcedefinitions
    - services
    - serviceaccounts
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
  - apiGroups:
    - "appdynamics.com"
    resources:
    - clusteragents
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: jenkins-jenkins-crb
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: jenkins
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: jenkins-self-provisioner-crb
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: self-provisioner
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ${PROJECT_NAME}
parameters:
- description: The name of the OCP project
  name: PROJECT_NAME
  required: true
